### ISSUE TITLE
Problem with mode Spectral Clouds! 

### ISSUE THREAD

**Issue by frekkia** [patrickdowling/superparasites#4]
I have a problem with the Spectral Clouds (Kammerl) mode, the module stops and freeze after a short while I use it what can it be?

**Comment by patrickdowling** [comment]
Hm, that's the first I've heard of something like that (which isn't saying much I guess).
To start with the basics, maybe that will yield some clues...
- what module (DIY?)
- is that just when first switching to the mode from another, or even when it starts in it
- what settings

**Comment by frekkia** [comment]
> Hm, that's the first I've heard of something like that (which isn't saying much I guess).
> To start with the basics, maybe that will yield some clues...
> 
> * what module (DIY?)
> * is that just when first switching to the mode from another, or even when it starts in it
> * what settings

Hi Patrick, Yes is diy. Either way, both when I change modes and when I start with that. Could it be a firmware flash problem? I used the original mutable-environment of pichenettes without changing it, then yesterday I read that you should use mqtthiqss stmlib, and update the gcc-arm-none-eabi. I tried to flash via Supercell's WAV and this seems to work well, not that problem anymore, but I'd be curious if the problem may be the original mutable suite. 
Thanks!

**Comment by patrickdowling** [comment]
Yes, the stmlibs do diverge in a few places so it's not a good idea to mix & match. If you build with the mutable stmlib it won't properly support the different MCU model.
The firmware was mostly tested using gcc 5.4 so that's what's recommended.

**Comment by frekkia** [comment]
> Yes, the stmlibs do diverge in a few places so it's not a good idea to mix & match. If you build with the mutable stmlib it won't properly support the different MCU model.
> The firmware was mostly tested using gcc 5.4 so that's what's recommended.

How do i update gcc? I use windows, I have tried but I have not succeeded!

**Comment by patrickdowling** [comment]
I can't say how it works on Windows. What I generally do (on OS X or Linux, so it should work within vagrant) is
- download the compiler version (e.g. from [here](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads) or [here](https://launchpad.net/gcc-arm-embedded/+download))
- Unpack it somewhere. Since I need multiple versions I have a whole bunch of them in `~/dev`
- In a shell, use something like `export TOOLCHAIN_PATH=~/dev/gcc-arm-none-eabi-5_4-2016q3/` to select which one to use
- make etc.
